# Generated by Django 3.2.7 on 2022-06-15 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_cadastro', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=64)),
                ('curso_selecionado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cursos.cursos')),
                ('token_cadastro', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.tokencadastro')),
            ],
        ),
    ]
