# Generated by Django 3.2.7 on 2022-06-13 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_token_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_cadastro', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='token_cadastro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.tokencadastro'),
        ),
    ]
